services:
  chronoframe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chronoframe
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
      # - STORAGE_PROVIDER=s3
      # - PROVIDER_S3_ENDPOINT=your-s3-endpoint
      # - PROVIDER_S3_BUCKET=your-bucket-name
      # - PROVIDER_S3_REGION=your-region
      # - PROVIDER_S3_ACCESS_KEY_ID=your-access-key
      # - PROVIDER_S3_SECRET_ACCESS_KEY=your-secret-key
      # - PROVIDER_S3_PREFIX=your-prefix
      # - PROVIDER_S3_CDN_URL=your-cdn-url
    restart: unless-stopped
    volumes:
      - ./data:/app/.data

  # database:
  #   image: postgres:15-alpine
  #   container_name: chronoframe_db
  #   environment:
  #     POSTGRES_DB: chronoframe
  #     POSTGRES_USER: chronoframe
  #     POSTGRES_PASSWORD: your-password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
